--[[
 An experiment in observing the self-magnetic field of the beam,
 i.e. the magnetic field generated by the beam itself.
 D.Manura, 2011-12-21.
 (c) 2011 Scientific Instrument Services, Inc. (SIMION 8.1 Licensed).
--]]

simion.workbench_program()

local MF = require "simionx.MField"

local CON = simion.import '../../contour/contourlib81.lua'

-- (x,y,z) positions of each particle at end of last time-step.
-- Keyed by ion_number.
local lastxs = {}
local lastys = {}
local lastzs = {}

local lines = {} -- data for magnetic field being built.

local field -- calculated magnetic field

-- Minimum step length for segments in Biot-Savart calculation.
-- Smaller is more accurate but increases calculation time.
local minstep = 5   -- mm

-- current in A per particle.
local ray_current_A = 0.2E-3 / 100

function segment.initialize()
  lastxs[ion_number] = ion_px_mm
  lastys[ion_number] = ion_py_mm
  lastzs[ion_number] = ion_pz_mm
end

function segment.other_actions()
  -- Line charge in this time-step is appended to the `lines` array.
  local x1,y1,z1 = lastxs[ion_number],lastys[ion_number],lastzs[ion_number]
  local x2,y2,z2 = ion_px_mm,ion_py_mm,ion_pz_mm
  local dx,dy,dz = x2-x1, y2-y1, z2-z1
  local d2 = dx*dx+dy*dy+dz*dz
  --print(x1,y1,z1, x2,y2,z2, d2)
  if d2 >= minstep^2 then
    lines[#lines+1] = MF.line_segment{
      current=ray_current_A,
      first=MF.vector(x1,y1,z1),
      last=MF.vector(x2,y2,z2)
    }
    lastxs[ion_number] = ion_px_mm
    lastys[ion_number] = ion_py_mm
    lastzs[ion_number] = ion_pz_mm
  end

end

function segment.initialize_run()
  lines = {} -- reset
  lastxs = {}
  lastys = {}
  lastzs = {}
end

function segment.terminate_run()
  -- Build magnetic field at end of run.
  print('# magnetic segments=', #lines)
  field = MF.combined_field(lines)
  
  -- Plot it too.
  CON.plot{func=field, x=100, npoints=20, mark=true, scale='median'}
  
  print('BField x,y,z in Gauss at 10 mm from axis is', field(100,10,0))
  print('(theoretical is (0, 4E-5, 0) Gauss)')
  simion.sleep(2)
end

-- In theory, the magnetic field generated by the beam could affect the
-- beam itself.  So, we optionally could rerun the simulation, using the
-- calculated magnetic field from the previous run.  However, the magnetic
-- field induced in this example is negligible (~ 10^-5 Gauss), far less
-- than Earth's magnetic field, so we don't even bother.
--[[
function segment.flym()
  local N = 3
  for i=1,N do
    --sim_rerun_flym = (i < N) and 0 or 1
    run()
  end
end
function segment.mfield_adjust()
  if field then --FIX
    ion_bfieldx_gu, ion_bfieldy_gu, ion_bfieldz_gu
      = field(ion_px_mm, ion_py_mm, ion_pz_mm)
  end
end
--]]
