simion.workbench_program()

-- Import HS1 collision model.
local HS1 = simion.import "collision_hs1.lua"

-- Number of example to test.
adjustable _mode = 1

-- Apply position-dependent background gas pressure, temperature, and/or
-- velocity. A number of different examples are provided below.  You can
-- quickly test them without editing this file by adjusting the _mode
-- variable from the SIMION Variables tab.
function HS1.init()
  if _mode == 0 then
    -- nothing
  elseif _mode == 1 then
    -- Define parabolic velocity vector profile.  Maximum velocity at y_gu = 0
    -- (center of duct).  Zero velocity at y_gu = +- 150 gu (sides of duct).
    function HS1.velocity(x_gu, y_gu, z_gu)
      local vx = (150-y_gu)*(150+y_gu) / 100
      return vx,0,0
    end
  elseif _mode == 1.1 then
    -- This is equivalent to the above.  It defines the x component of the
    -- velocity vector (and the components in the other dimensions are
    -- by default 0).
    function HS1.velocity_x(x_gu, y_gu, z_gu)
      local vx = (150-y_gu)*(150+y_gu) / 100
      return vx
    end
  elseif _mode == 1.2 then
    -- This is equivalent to the above.
    -- Define velocity as a function of position in workbench
    -- units (mm) using ion_px_mm/ion_py_mm/ion_pz_mm variables.  In this example,
    -- the PA scaling factor is 1mm/gu and the PA is positioned at the workbench origin,
    -- so the distinction doesn't matter.
    function HS1.velocity()
      local vx = (150-ion_py_mm)*(150+ion_py_mm) / 100
      return vx,0,0
    end
  elseif _mode == 1.3 then
    -- This is equivalent to the above.
    -- Define field velocity field numerically via a text file.

    -- The CSV file was generated by the make.lua program.
    -- We'll rebuild here just in case.
    dofile 'make.lua'

    local FieldArray = require "simionx.FieldArray"
    HS1.velocity = FieldArray("velocity.csv")

    -- Alternately, we may write
    --
    --   HS1.velocity_x = FieldArray("velocity.csv")
    --
    -- which uses only the first component of the velocity.csv vectors.
    -- Another alternative is to wrap the array inside a function:
    --
    --   local fa = FieldArray("velocity.csv")
    --   function HS1.velocity(x_gu, y_gu, z_gu)
    --     local vx,vy,vz = fa(x_gu,y_gu,z_gu)
    --     -- vx = vx + 1  -- override vector
    --     -- print('DEBUG:', x_gu,y_gu,z_gu, vx,vy,vz)
    --     return vx,vy,vz
    --   end
  elseif _mode == 1.4 then
    -- This is equivalent to the above.
    -- This will only run under SIMION 8.1.


    -- Before running this, enter the following into the SIMION
    -- command bar:
    --   dofile 'make.lua'
    -- The above will generate the velocity_x.pa array.
    assert(simion.pas, 'This example requires SIMION 8.1.')

    -- The PA arrays were generated by the make.lua program.
    -- We'll rebuild here just in case.
    dofile 'make.lua'

    -- First make sure P,T,v arrays from previous runs are unloaded
    -- to prevent accumulating multiple copies in memory.  Then install
    for i=#simion.pas,1,-1 do
      print(i,simion.pas[i].filename)
      if simion.pas[i].filename == 'velocity_x.pa' or
         simion.pas[i].filename == 'temperature.pa'
      then
        simion.pas[i]:close()
      end
    end
    HS1.velocity_x = simion.pas:open('velocity_x.pa')

    -- Optionally gradient temperature too
    -- (with no y symmetry + y position shift)
    --   local pa = simion.pas:open('temperature.pa')
    --   HS1.temperature = function(xgu,ygu,zgu)
    --     return pa(xgu,ygu+150,zgu)
    --   end

    -- Note: alternately, we could add and position the P,T,v arrays into the
    -- workbench and then access the arrays via simion.wb.instances[i].pa .
    -- This will avoid the loading/unloading above.
  elseif _mode == 2 then
    -- Define temperature gradient.
    function HS1.temperature(x_gu, y_gu, z_gu)
      local T = 1 + (150+y_gu) * 1.0
      return T
    end
  elseif _mode == 2.1 then
    -- This is equivalent to the above.
    -- Define temperature gradient numerically via a text file.

    -- The CSV file was generated by the make.lua program.
    -- We'll rebuild here just in case.
    dofile 'make.lua'

    local fa = require "simionx.FieldArray" ("temperature.csv")
    HS1.temperature = fa
  elseif _mode == 3 then
    -- Define a pressure gradient.
    function HS1.pressure(x_gu, y_gu, z_gu)
      local T = 1 + (150+y_gu) / 100
      return T
    end
    -- And with constant velocity.
    function HS1.velocity_x(x_gu, y_gu, z_gu)
      return 10
    end
    -- Alternately do "_vy_bar_gas_mmusec = 10" here.
  else
    error("Adjustable variable _mode is out of range")
  end
end


-- ## Additional comments ##
--
-- To check the above, you may adding print statements inside the functions.  Example:
--
--    function HS1.temperature(x_gu, y_gu, z_gu)
--      local T = 1  + (150+y_gu) * 1.0
--      print('DEBUG,T=', T)
--      return T
--    end
--
