--[[
 fluent_ip_to_simion_pas.lua
 Converts ANSYS Fluent Interpolation (.ip) file to SIMION PA files.
 
 The .ip file contains Fluent calculated flow data parameters (e.g.
 x/y/z coordinates of mesh points, x/y/z components of velocity, pressure
 and/or temperature) after interpolating onto some mesh.
 For SIMION purposes, we prefer this mesh to be a uniform rectilinear
 grid to allow easy representation as SIMION PA files.
 The .ip file can be generated by "File > Interpolate" in Fluent.

 This will create one SIMION PA for each flow parameter.  Any points not
 defined in the Fluent file currently default to 0.
 
 Some adjustment to this program may be necessary for your own purposes.
 
 WARNING: Fluent defaults to SI units, but the user may change this.
 SIMION units are by default mm for distance and
 mm/microsecond for velocity.  See SIMION SDS and HS1 for flow units
 they use.  This program makes some attempt to convert these, but
 you may need to rescale units.
 
 WARNING: For best precision, take care about whether parameters
 represent the corners or centers of grid cells.  Flows may be
 off by one grid unit if you don't accounts for this when
 creating PA's and interpreting them in SIMION.  So, please check
 if maximum precision is desired.

 WARNING: In the Fluent file, the x/y/z coordinates of the points are
 not necessarily in lexographic order nor fill the entire rectangular array.
 More significantly, the points tend to not exactly align to the
 rectilinear grid; rather, points that you would expect to have identical
 values of some x/y/z coordinate actually tend to have a small variance
 in that coordinate.
 Therefore, to interpret this data file, we resort to some heuristics to
 define how to round to the nearest grid point.
 
 A typical way to plot velocity vectors (using "contourlib81" in the "contour"
 example), assuming the vx,vy,vz arrays are PA instances #1-3 on the PA
 Instances list on the View screen PAs tab, is as follows
 (in SIMION >= 8.1.1.0):
 
   local vxinst = simion.wb.instances[1]
   local vyinst = simion.wb.instances[2]
   local vzinst = simion.wb.instances[3]
   local function velocity(x,y,z)
     return vxinst:potential_wc(x,y,z),
            vyinst:potential_wc(x,y,z),
            vzinst:potential_wc(x,y,z)
   end
   simion.import'../contour/contourlib81.lua'.plot{func=velocity, mark=true}
 
 D.Manura,2012-07-16,2012-03.
 (c) 2012 Scientific Instrument Services, Inc. (Licensed SIMION 8.1)
--]]

-- Name of Fluent input file.
local filename = 'fluent_example.ip'

-- Open Fluent file.
local fh = assert(io.open(filename, 'r'))

-- Load header from .ip file.
local fluent_version = fh:read'*n'
local dimension = fh:read'*n'
local num_points = fh:read'*n'
local num_fields = fh:read'*n'
local field_names = {'x', 'y'}
if dimension == 3 then field_names[#field_names+1] = 'z' end
field_names.start = #field_names + 1
fh:read'*l' -- eat newline
for i=1,num_fields do
  local name = fh:read'*l'
  field_names[#field_names+1] = name
end

-- Dump headers (debugging).
print('Fluent file version:', fluent_version)
    -- expects 1 (Fluent 5) or 2 (Fluent 6)
print('Dimension:', dimension)
print('Num points:', num_points)
print('Fields:', num_fields)
for i=1,num_fields do
  print('', field_names[i])
end

-- Read data points from .ip file.
local fields = {}
for i=1,#field_names do
  local data = {}
  for j=1,num_points do
    local num = assert(fh:read'*n')
    data[#data+1] = num
  end
  fields[field_names[i]] = data  
end
local rest = fh:read'*a'
if not rest:match'^%s*$' then
  error('extra data found at end of file: ['..rest..']')
end

-- Close Fluent file.
fh:close()

-- If you wish to swap coordinates, you could do things
-- like this here:
--[[
fields.x, fields.z = fields.z, fields.x
fields['x-velocity'], fields['z-velocity'] = fields['z-velocity'], fields['x-velocity']
--]]

-- The following code has been removed since SDS expects gas velocity units
-- to be in m/s (same as Fluent SI units).
-- 
-- Convert velocity units: m/s (SI units) --> mm/usec (SIMION units).
-- local MMUS_PER_MS = 0.001
-- for _, name in ipairs(field_names) do
--   if name == 'x-velocity' or name == 'y-velocity' or name == 'z-velocity' then
--     for j=1,num_points do
--       fields[name][j] = fields[name][j] * MMUS_PER_MS
--     end
--   end
-- end

-- Get unique, sorted list of values for each x/y/z coordinate.
local function sort_coords(t)
  local tt = {}
  local found = {}
  for _,v in ipairs(t) do
    if not found[v] then
      tt[#tt+1] = v
      found[v] = true
    end
  end
  table.sort(tt)
  return tt
end
local xs = sort_coords(fields.x)
local ys = sort_coords(fields.y)
local zs = sort_coords(fields.z or {0})

--[[
-- Dump unique, sorted coordinates.
print 'xs'
for i,v in ipairs(xs) do print(v) end
print 'ys'
for i,v in ipairs(ys) do print(v) end
print 'zs'
for i,v in ipairs(zs) do print(v) end
print '--'
for i=1,#fields.x do
  print(fields.x[i], fields.y[i], fields.z[i])
end
--]]

-- Rounds value to nearest integer.
local function round(x)
  return math.floor(x + 0.5)
end

-- Compute statistics for coordinate.
-- `xmin` and `xmax` and min and max values of coordinate respectively.
-- `dx` is approximate distance between successive values.
-- `npoints` is number of data points.
-- WARNING: uses heuristics to determine grid and might not work in all cases.
local function coord_stats(t)
  local min = t[1]
  local max = t[#t]
  -- Find maximum distance between points.
  local dmax = 0
  for i=1,#t do
    if i > 1 then
      local du = t[i] - t[i-1]
      dmax = math.max(dmax, du)
    end
  end
  if dmax == 0 then
    return min, max, 1E+100, 1
  else
    -- Find average distance between points close to maximum distance.
    -- There tends to be some variation from the maximum.
    local dsum, dcount = 0, 0
    for i=1,#t do
      if i > 1 then
        local du = t[i] - t[i-1]
        if math.abs(math.abs(du / dmax) - 1) < 0.1 then
          dsum = dsum + du
          dcount = dcount + 1
        end
      end
    end
    local dave = dsum / dcount
    local offset = ((max-min)/dave + 0.5) % 1 - 0.5
    if math.abs(offset) > 0.1 then  -- allow small fraction of gu error
      error('error: offset='..offset)
    end
    -- Finish stats.
    local npoints = round((max - min) / dmax) + 1
    local d = npoints == 1 and 1E+100 or (max-min)/(npoints-1)
    return min, max, d, npoints
  end
end
local xmin, xmax, dx, nx = coord_stats(xs)
local ymin, ymax, dy, ny = coord_stats(ys)
local zmin, zmax, dz, nz = coord_stats(zs)

-- Dump coordinate stats.
print('nx=', nx, 'xmin=', xmin, 'xmax=', xmax, 'dx=', dx)
print('ny=', ny, 'ymin=', ymin, 'ymax=', ymax, 'dy=', dy)
print('nz=', nz, 'zmin=', zmin, 'zmax=', zmax, 'dz=', dz)

if nx*ny*nz < num_points then  -- note: Fluent may omit points
  error(('Failed to intepret grid size: %d x %d x %d < %d'):format(
    nx,ny,nz, num_points))
end

-- Force rotation if coordinate other than z has one point.
-- SIMION PA requires nz == 1 if array has 2D symmetry.
if (nx == 0 and 1 or 0) + (ny == 0 and 1 or 0) + (nz == 0 and 1 or 0) > 1 then
  error('multiple coordinates have only one point.')
end
if nx == 1 then
  print 'WARNING: forcing rotation: y,z,x -> x,y,z so that nz=1'
  fields.x, fields.y, fields.z =
  fields.y, fields.z, fields.x
  xmin,xmax,dx,nx, ymin,ymax,dy,ny, zmin,zmax,dz,nz =
  ymin,ymax,dy,ny, zmin,zmax,dz,nz, xmin,xmax,dx,nx
  assert(nz == 1)
elseif ny == 1 then
  print 'WARNING: forcing rotation: z,x,y -> x,y,z so that nz=1'
  fields.x, fields.y, fields.z =
  fields.z, fields.x, fields.y
  xmin,xmax,dx,nx, ymin,ymax,dy,ny, zmin,zmax,dz,nz =
  zmin,zmax,dz,nz, xmin,xmax,dx,nx, ymin,ymax,dy,ny
  assert(nz == 1)
end

-- Create PA object headers.
local pas = {}
local MM_PER_M = 1000 -- assuming positions in original file in units of m.
for i=field_names.start, #field_names do
  local pa = simion.pas:open()
  pa:size(nx,ny,nz)
  pa.filename = field_names[i] .. '.pa'  -- note: you may wish to change this
  pa.refinable = false  -- prevent SIMION prompting to refine this PA.
  pa.dx_mm = MM_PER_M * dx
  pa.dy_mm = MM_PER_M * dy
  if nz > 1 then pa.dz_mm = MM_PER_M * dz end
  
  -- optionally enable mirroring like this:
  --pa.mirror_x = true
  
  pas[#pas+1] = pa
end

-- Gets integer index for given real number coordinate value `u`,
-- assuming `umin` is value at index 0 and `du` is the approximate
-- difference in `u` between successive indices.
local function coord_round(u, umin, du)
  local offset = ((u - umin)/du + 0.5) % 1 - 0.5
  if math.abs(offset) > 0.1 then -- off by >10% from grid point.
    error(('ASSERT: position %g is %d % away from grid point'):format(
          u, offset*100))
  end
  return round((u - umin)/du)
end

-- Fill PA data points.
for i=1,#fields.x do
  local xi = coord_round(fields.x[i], xmin, dx)
  local yi = coord_round(fields.y[i], ymin, dy)
  local zi = nz == 1 and 0 or coord_round(fields.z[i], zmin, dz)
  for j=field_names.start,#field_names do
    local name = field_names[j]
    pas[j-field_names.start+1]:potential(xi,yi,zi, fields[name][i])
  end
end

-- Save PA's.
for i=1,#pas do
  pas[i]:save()
end

print 'DONE'
